/**
 * Commit-message and repository-file helpers.
 *
 * This module is deliberately free of Node built-ins so the web editor can
 * import it to preview a message without pulling the planner (and `node:fs`)
 * into the browser bundle.
 */

export const DEFAULT_MESSAGE_TEMPLATE =
  "git-mosaic: pixel {date} ({index}/{total})";

export interface MessageValues {
  date: string;
  timestamp: string;
  index: number;
  total: number;
  intensity: number;
  project: string;
}

export function renderMessage(template: string, values: MessageValues): string {
  return template.replaceAll(
    /\{(date|timestamp|index|total|intensity|project)\}/g,
    (_, key: string) => String(values[key as keyof MessageValues]),
  );
}

/**
 * Renders the message a plan would produce, so a template can be previewed
 * before a single commit exists.
 */
export function previewCommitMessage(
  template: string,
  values?: Partial<MessageValues>,
): string {
  return renderMessage(template, {
    date: "2025-03-14",
    timestamp: "2025-03-14T12:00:00.000Z",
    index: 1,
    total: 4,
    intensity: 3,
    project: "my-mosaic",
    ...values,
  });
}

/** Default README for a generated repository: it discloses what the history is. */
export function defaultReadme(projectName: string, period: string): string {
  return `# ${projectName}

This repository's commit history was generated by git-mosaic as contribution
artwork covering ${period}. It does not represent the timing or volume of
software development.
`;
}
